paths:
  log: "example_file/"
  rule: "example_file/rules/"
  new_rules: "example_file/"

file_names:
  log: "alert_json.txt"
  new_rules: "rule_test"

ssh:
  dispositovo_1: 
    user: "user"
    addr: "172.18.32.45"
    path: "~/newRules/newRule.rules"
  dispositovo_2:
    user: "user" 
    addr: "127.0.1.1"
    path: "~/newRules/newRule.rules"