paths:
  log: "/var/snort/"
  rule: "/usr/local/etc/rules/"
  new_rules: "/home/user/rule/"
  ssh_addr: "/usr/local/etc/snort/ssh/"

file_name:
  log: "alert_json.txt"
  new_rules: "new_rules.rules"
  ssh: ssh_address_and_path.txt

ssh:
  dispositovo_1: 
    addr: "user@172.18.32.45"
    path: "/newRules/newRule.rules"