paths:
  log: "/var/snort/"
  rule: "/usr/local/etc/rules/"
  new_rules: "/home/user/rule/"

file_names:
  log: "alert_json.txt"
  new_rules: "new_rules.rules"

ssh:
  dispositovo_1: 
    addr: "user@172.18.32.45"
    path: "~/newRules/newRule.rules"